parameters:
    env(CONSUMER_ID): '0'

framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            warmup_date:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/warmup_date/symfony/consumer-%env(CONSUMER_ID)%?auto_setup=true'
            rates_preload:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/rates_preload/symfony/consumer-%env(CONSUMER_ID)%?auto_setup=true'
            index_rur:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/index_rur/symfony/consumer-%env(CONSUMER_ID)%?auto_setup=true'
            index_base:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/index_base/symfony/consumer-%env(CONSUMER_ID)%?auto_setup=true'

        routing:
            'App\Domain\Rates\Message\WarmupDateMessage': warmup_date
            'App\Domain\Rates\Message\RatesPreloadMessage': rates_preload
            'App\Domain\Ticker\Message\IndexRurMessage': index_rur
            'App\Domain\Ticker\Message\IndexBaseMessage': index_base

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
