version: "3.5"

networks:
  cbrw:
    driver: bridge
    name: cbrw
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/24

services:
  cbrw-web:
    hostname: cbrw-web
    container_name: cbrw-web
    image: nginx:latest
    ports:
      - "8800:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./:/var/www
      - ./var/nginx:/var/log/nginx
    links:
      - cbrw-php
    networks:
      - cbrw

  cbrw-php:
    hostname: cbrw-php
    container_name: cbrw-php
    restart: always
    build:
      context: ./
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www
      - ./var/tmp:/tmp
      - ./var:/var/www/var
      - ./config/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf:ro
      - ./var/supervisor:/var/log/supervisor
    environment:
      XDEBUG_MODE: debug,profile
      XDEBUG_CONFIG: client_host=192.168.220.1 client_port=9003 mode=debug,profile start_with_request=yes discover_client_host=false
      PHP_IDE_CONFIG: serverName=Docker
      TZ: ${TZ}
    links:
      - cbrw-redis
    networks:
      - cbrw

  cbrw-redis:
    container_name: cbrw-redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cbrw
