services:
    _defaults:
        autowire: true

    App\Domain\Rates\Service\RatesProviderInterface:
        class: App\Domain\Rates\Service\CbrRatesProvider
        public: true

    App\Domain\Rates\Service\RatesParserInterface:
        class: App\Domain\Rates\Service\CbrRatesParser
        public: true
