services:
    _defaults:
        autowire: true

    App\Service\RatesProviderInterface:
        class: App\Service\CbrRatesProvider
        public: true

    App\Service\RatesParserInterface:
        class: App\Service\CbrRatesParser
        public: true
